name: Main Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'app/backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore app/backend/NewerDown.sln

      - name: Build
        run: dotnet build --no-restore app/backend/NewerDown.sln --configuration Release

      - name: Apply Migrations
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          dotnet tool install --global dotnet-ef
          cd app/backend
          dotnet ef database update --project NewerDown.Infrastructure/NewerDown.Infrastructure.csproj --startup-project NewerDown.API/NewerDown.API.csproj --context ApplicationDbContext

      - name: Publish API
        run: dotnet publish app/backend/NewerDown.API/NewerDown.API.csproj -c Release -o ./publish-api --no-build

      - name: Publish Admin Panel
        run: dotnet publish app/backend/NewerDown.AdminPanel/NewerDown.AdminPanel.csproj -c Release -o ./publish-admin --no-build

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish-api
          path: ./publish-api

      - name: Upload Admin artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish-admin
          path: ./publish-admin

      - name: Execute unit tests
        run: dotnet test app/backend/NewerDown.Application.UnitTests/NewerDown.Application.UnitTests.csproj

      - name: Execute integration tests
        run: dotnet test app/backend/NewerDown.IntegrationTests/NewerDown.IntegrationTests.csproj

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write 
      contents: read

    steps:
      - name: Download API artifact
        uses: actions/download-artifact@v4
        with:
          name: publish-api
          path: ./publish-api

      - name: Download Admin artifact
        uses: actions/download-artifact@v4
        with:
          name: publish-admin
          path: ./publish-admin

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-newerdown'
          slot-name: 'Production'
          package: ./publish-api

      - name: Deploy Admin Panel to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-newerdown-admin'
          slot-name: 'Production'
          package: ./publish-admin